### PR TITLE
Test for -static support before using it

### PR DESCRIPTION
**Pull request by asottile**
A potential solution for #152  -- need to check this on macos first.  Here's the linux output:

```
$ python setup.py bdist_wheel
running bdist_wheel
running build
running build_cexe
supports -static... yes
cc -c dumb-init.c -o build/temp.linux-x86_64-2.7/dumb-init.o
cc build/temp.linux-x86_64-2.7/dumb-init.o -o build/scripts-2.7/dumb-init -static
installing to build/bdist.linux-x86_64/wheel
running install
running install_egg_info
running egg_info
writing dumb_init.egg-info/PKG-INFO
writing top-level names to dumb_init.egg-info/top_level.txt
writing dependency_links to dumb_init.egg-info/dependency_links.txt
reading manifest file 'dumb_init.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'dumb_init.egg-info/SOURCES.txt'
Copying dumb_init.egg-info to build/bdist.linux-x86_64/wheel/dumb_init-1.2.0.data/purelib/dumb_init-1.2.0.egg-info
running install_scripts
running install_cexe
creating build/bdist.linux-x86_64/wheel/dumb_init-1.2.0.data/scripts
copying build/scripts-2.7/dumb-init -> build/bdist.linux-x86_64/wheel/dumb_init-1.2.0.data/scripts
creating build/bdist.linux-x86_64/wheel/dumb_init-1.2.0.dist-info/WHEEL
```

### CODE REVIEW

**Comment by asottile** [comment]
Here's the macos output, I'll silence the subprocess:

```
$ python setup.py bdist_wheel
running bdist_wheel
running build
running build_cexe
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
supports -static... no
creating build
creating build/temp.macosx-10.12-intel-2.7
cc -c dumb-init.c -o build/temp.macosx-10.12-intel-2.7/dumb-init.o
creating build/scripts-2.7
cc build/temp.macosx-10.12-intel-2.7/dumb-init.o -o build/scripts-2.7/dumb-init
installing to build/bdist.macosx-10.12-intel/wheel
running install
running install_egg_info
running egg_info
creating dumb_init.egg-info
writing dumb_init.egg-info/PKG-INFO
writing top-level names to dumb_init.egg-info/top_level.txt
writing dependency_links to dumb_init.egg-info/dependency_links.txt
writing manifest file 'dumb_init.egg-info/SOURCES.txt'
reading manifest file 'dumb_init.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'dumb_init.egg-info/SOURCES.txt'
Copying dumb_init.egg-info to build/bdist.macosx-10.12-intel/wheel/dumb_init-1.2.0.data/purelib/dumb_init-1.2.0-py2.7.egg-info
running install_scripts
running install_cexe
creating build/bdist.macosx-10.12-intel/wheel/dumb_init-1.2.0.data/scripts
copying build/scripts-2.7/dumb-init -> build/bdist.macosx-10.12-intel/wheel/dumb_init-1.2.0.data/scripts
creating build/bdist.macosx-10.12-intel/wheel/dumb_init-1.2.0.dist-info/WHEEL
creating '/private/tmp/dumb-init/dist/dumb_init-1.2.0-py2.py3-none-macosx_10_12_intel.whl' and adding '.' to it
adding 'dumb_init-1.2.0.data/scripts/dumb-init'
adding 'dumb_init-1.2.0.dist-info/DESCRIPTION.rst'
adding 'dumb_init-1.2.0.dist-info/metadata.json'
adding 'dumb_init-1.2.0.dist-info/top_level.txt'
adding 'dumb_init-1.2.0.dist-info/WHEEL'
adding 'dumb_init-1.2.0.dist-info/METADATA'
adding 'dumb_init-1.2.0.dist-info/RECORD'
```

**Comment by asottile** [comment]
now with less error spew:

```
$ python setup.py bdist_wheel
running bdist_wheel
running build
running build_cexe
supports -static... no
cc -c dumb-init.c -o build/temp.macosx-10.12-intel-2.7/dumb-init.o
cc build/temp.macosx-10.12-intel-2.7/dumb-init.o -o build/scripts-2.7/dumb-init
installing to build/bdist.macosx-10.12-intel/wheel
running install
running install_egg_info
running egg_info
writing dumb_init.egg-info/PKG-INFO
writing top-level names to dumb_init.egg-info/top_level.txt
writing dependency_links to dumb_init.egg-info/dependency_links.txt
reading manifest file 'dumb_init.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'dumb_init.egg-info/SOURCES.txt'
Copying dumb_init.egg-info to build/bdist.macosx-10.12-intel/wheel/dumb_init-1.2.0.data/purelib/dumb_init-1.2.0-py2.7.egg-info
running install_scripts
running install_cexe
creating build/bdist.macosx-10.12-intel/wheel/dumb_init-1.2.0.data/scripts
copying build/scripts-2.7/dumb-init -> build/bdist.macosx-10.12-intel/wheel/dumb_init-1.2.0.data/scripts
creating build/bdist.macosx-10.12-intel/wheel/dumb_init-1.2.0.dist-info/WHEEL
creating '/private/tmp/dumb-init/dist/dumb_init-1.2.0-py2.py3-none-macosx_10_12_intel.whl' and adding '.' to it
adding 'dumb_init-1.2.0.data/scripts/dumb-init'
adding 'dumb_init-1.2.0.dist-info/DESCRIPTION.rst'
adding 'dumb_init-1.2.0.dist-info/metadata.json'
adding 'dumb_init-1.2.0.dist-info/top_level.txt'
adding 'dumb_init-1.2.0.dist-info/WHEEL'
adding 'dumb_init-1.2.0.dist-info/METADATA'
adding 'dumb_init-1.2.0.dist-info/RECORD'
```

**Comment by asottile** [comment]
yeah 1.2.0.post1 seems fine to me, we didn't actually change any dumb-init code since 1.2.0

**Comment by asottile** [comment]
oh actually 1.2.1 due to https://github.com/Yelp/dumb-init/commit/7623fb4271b299a504b2db55c852eba60a727aa9 ?

**Comment by chriskuehl** [comment]
Yeah, 1.2.1 sounds okay, though that commit doesn't actually change any "real" behavior (it fixes a bug, bug the bug only affects the debug logging output).

**Pull request merged**
