### PR TITLE
Reduce binary size using musl

### PR DESCRIPTION
**Pull request by kscherer**

### CODE REVIEW

**Comment by chriskuehl** [comment]
This looks great to me! We were originally using musl but dropped it because it wasn't available on some of our legacy systems where we were doing the build -- but I don't think that applies anymore now.

**Comment by kscherer** [comment]
It took me a little while to figure out the build system. Using docker to do the build in debian jesse solves the legacy issue.

**Comment by chriskuehl** [comment]
Yup, confirmed it works well for us! Just waiting for Circle to hopefully complete successfully this time and then I'll merge.

Thanks for the solid PR!

**Comment by chriskuehl** [comment]
Success! I'll merge and release a new version shortly. Thanks again!

**Comment by kscherer** [comment]
Thank you for providing dumb-init! It nicely solves one of the problems of running normal processes in docker. The other solutions involved python3 or full supervisor/init system.

**Comment by chriskuehl** [comment]
Just released v1.0.0 containing your changes. The binary and Debian package are both much, much smaller :)

https://github.com/Yelp/dumb-init/releases/tag/v1.0.0

**Pull request merged**
