### PR TITLE
Use NSIG instead of hardcoding the signal count

### PR DESCRIPTION
**Pull request by msavage20**

### CODE REVIEW

**Comment by asottile** [comment]
Fails the tests while attempting to register signal handler for 32. (SIGWAITING)

**Comment by msavage20** [comment]
32+ are real-time signals, which are trickier to work with. If you want to deal with those, you'll want to use the `SIGRTMIN`/`SIGRTMAX` macros to register them, and I believe you need to use sigqueue(3) instead of kill(2) to send them.

**Comment by chriskuehl** [comment]
I'm going to close this PR for now since we can't merge it in its current state. Thanks for bringing the issue to our attention, though!

I'm not aware of any common uses of signals above 32 in practice but I think we'd be happy to take a PR which adds the capability (plus some tests to ensure we don't regress) as long as it doesn't overly complicate things.

(If this is preventing someone from using dumb-init, could you file a new issue with a short description and the program which uses the high-numbered signals?)

**Comment by msavage20** [comment]
> I'm not aware of any common uses of signals above 32 in practice

Me neither. :d

This PR was just suggesting the use of `NSIG` for clarity, but I can't figure out where signal 32 is being raised in the test suite.

**Pull request closed without merging**
