### PR TITLE
Add process group support

### LINKED ISSUE #4: create, send signal to a process group
Use case is a bash script like so:

```#!bash
yes oh, hi! | pv -qL 10 &
yes error | pv -qL 10 >&2
```

When dumb-init gets sigterm (or any other signal), I want the whole process tree (bash, yes, pv, yes, pv) to get the same signal. 

Implementation:
 * on startup dumb-init initiates a process group:
   http://man7.org/linux/man-pages/man2/setsid.2.html
 * on signal, dumb-init sends that signal to the process group it created:
   http://man7.org/linux/man-pages/man2/kill.2.html

### PR DESCRIPTION
**Pull request by chriskuehl**
Still working on the tests for this, but feel free to do an initial review. (My last attempt at tests ended up not working so well, but I have another idea that should work better.)

This should resolve #4

### CODE REVIEW

**Comment by bukzor** [comment]
setpgid belongs in the child section, just before the exec.

Also, I expected setsid. I believe it's the usual way to implement this.

**Comment by bukzor** [comment]
I believe you want to use vfork and setpgid 0

**Comment by bukzor** [comment]
This article was very informative http://www.informit.com/articles/article.aspx?p=366888&seqNum=8

**Comment by chriskuehl** [comment]
@bukzor sorry, should have provided more context. The reason it's implemented this way is:

* if we root the process group at the dumb-init process, then when we send signals to the process group, dumb-init will also receive that signal, which creates a feedback loop (dumb init receives signal, proxies it, receives that same signal again, ...).
  
  instead, by rooting it at the child spawned by dumb-init, we can signal the entire process group without the feedback loop. I don't know a better way to handle that.

* I think this is the correct use of process groups:

    > Each process is a member of a process group, which is a collection of one or more processes generally associated with each other for the purposes of job control. The primary attribute of a process group is that signals may be sent to all processes in the group: a single action can terminate, stop, or continue all processes in the same process group.
    > 
    > Each process group is identified by a process group ID (pgid), and has a process group leader. The process group ID is equal to the pid of the process group leader. Process groups exist so long as they have one remaining member. Even if the process group leader terminates, the process group continues to exist.
    > 
    > When a new user first logs into a machine, the login process creates a new session that consists of a single process, the user's login shell. The login shell functions as the session leader. The pid of the session leader is used as the session ID. A session is a collection of one or more process groups. Sessions arrange a logged-in user's activities, and associate that user with a controlling terminal, which is a specific tty device that handles the user's terminal I/O. Consequently, sessions are largely the business of shells. In fact, nothing else really cares about them.
    > 
    > While process groups provide a mechanism to address signals to all of their members, making job control and other shell functions easy, sessions exist to consolidate logins around controlling terminals.
    > https://www.safaribooksonline.com/library/view/linux-system-programming/0596009585/ch05s06.html

    I originally tried using session IDs but was getting EPERM and after additional reading concluded process groups were a better approach. If you think sessions are better I can switch back to that and debug the EPERM issues (I didn't attempt that).

vfork does look correct, I'll switch to that.

**Comment by chriskuehl** [comment]
Oh, I get your point about moving it before the exec, agreed.

**Comment by bukzor** [comment]
As above, the setpgid 0 belongs in the child, between fork and exec. Vfork
eliminates the race condition.

--phone is hard.

**Comment by chriskuehl** [comment]
I've added tests for the new functionality (and another test to ensure the mode with process groups disabled still works), plus moved the process group setting to the child half of the fork before exec-ing the new process. This has a benefit of also eliminating a race condition (the child exits before we set the process group, and then we get an `EACCES` error trying to set the process' process group).

However, we can't actually use vfork without invoking undefined behavior:

> The vfork() function has the same effect as fork(2), except that **the behavior is undefined if** the process created by vfork() either modifies any data other than a variable of type pid_t used to store the return value from vfork(), or returns from the function in which vfork() was called, **or calls any other function before successfully calling _exit(2) or one of the exec(3) family of functions**.

`fork` should be safe and it looks like on modern systems they are effectively the same in terms of performance (copy-on-write avoids copying all the memory).

So not only can we not call `setpgid`, but we also couldn't use `fprintf` which we use for outputting debug lines.

**Comment by bukzor** [comment]
The opengroup rationale indicates that vfork was invented specifically for
this purpose: calling setpgid before exec.

http://pubs.opengroup.org/onlinepubs/009695399/functions/setpgid.html#tag_03_658_08

**Comment by chriskuehl** [comment]
@bukzor interesting, thanks for showing that. I can't find anything confirming or denying if that is also true in Linux, except that it's not mentioned in the man page anywhere.

I think fork is still probably the correct choice, though. There's a lot of literature online saying that vfork is often incompatible between OSes, it's easy to hit undefined behavior, and in general there aren't many benefits over fork. Here's a good example that lists some issues:
https://www.securecoding.cert.org/confluence/pages/viewpage.action?pageId=1703954

Also, since we've moved the `setpgid`, I don't see any race conditions left. Do you?

**Comment by bukzor** [comment]
The rationale mentions both the parent and child should attempt to setpgid
"it doesn't matter which succeeds first", but I don't quite understand why.

**Comment by chriskuehl** [comment]
So, [at least one person](https://www.dragonflybsd.org/mailarchive/kernel/2005-04/msg00268.html) seems to think it's "probably" ok to call `setpgid` from the child process created by vfork, though I can't find anything authoritative confirming that (besides that RATIONALE section you linked which I'm not sure if applies to Linux).

I don't think we get any benefit out of `vfork` over `fork`, do you?

**Comment by bukzor** [comment]
That's fine. I'll try to review this in detail today.

--phone is hard.

**Comment by chriskuehl** [comment]
@bukzor itests pass, I think this is ready to merge / review

**Pull request merged**
